title: Aditya Shriwastava
author:
  name: Aditya Shriwastava
  email: adityashriwastava7@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  My poorly written personal blog!
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: github,         user_url: "https://github.com/aditya-shriwastava" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/aditya-shriwastava-b07849143/" }
    - { platform: twitter,        user_url: "https://twitter.com/AdityaS04570638" }
    - { platform: youtube,        user_url: "https://www.youtube.com/channel/UCFpDGtX8lCK4O5mWY74GhTw" }

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
